name: Docker Image CI to ACR

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: test-ci
  IMAGE_TAG: 1.0.${{ github.run_number }} # GITHUB_RUN_NUMBER }}
  registry: ${{ secrets.ACR_ENDPOINT }}
  username: ${{ secrets.ACR_USERNAME }}
  password: ${{ secrets.ACR_PASSWORD }}


jobs:

  build:
    runs-on: ubuntu-latest
# Set directory for CI subfolder
    defaults:
      run:
        working-directory: test-ci
# Checkout 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
# Login to ACR
    # - name: Log into registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ${{ secrets.ACR_ENDPOINT }}
    #     username: ${{ secrets.ACR_USERNAME }}
    #     password: ${{ secrets.ACR_PASSWORD }}
#Build and Push Docker Image to ACR
    - name: Build the Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
#        docker build -t ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
#        docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Update Image Version in the related HelmChart values.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        # valueFile: 'test-ci/values.yaml'
        # propertyPath: 'image.tag'
        # value: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 
        # branch: test
        # targetBranch: main
        # createPR: true
        # message: 'Update Image Version to ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'

        valueFile: 'test-ci/values.yaml'
        branch: deployment
        targetBranch: main
        createPR: 'true'
        description: Test GitHub Action
        message: 'Update All Images' 
        title: 'Version Updates '
        changes: |
          {
            "test-ci/values.yaml": {
              "image.tag": "${{ env.IMAGE_TAG }}"
            }
          }