apiVersion: apps/v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
  annotations:
spec:
  matchLabels:
    app: wordpress
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
